### ISSUE TITLE
Multus: error in invoke Delegate add - "sriov": netplugin failed but error parsing its diagnostic message "": unexpected end of JSON input

### ISSUE THREAD

**Issue by ccmin** [intel/sriov-cni#110]
[root@master ~]# kubectl describe pod pod-case-03 
Name:         pod-case-03
Namespace:    default
Priority:     0
Node:         master/192.168.1.203
Start Time:   Tue, 03 Dec 2019 11:15:10 +0800
Labels:       <none>
Annotations:  k8s.v1.cni.cncf.io/networks: sriov-conf-1
              k8s.v1.cni.cncf.io/networks-status: 
              kubectl.kubernetes.io/last-applied-configuration:
                {"apiVersion":"v1","kind":"Pod","metadata":{"annotations":{"k8s.v1.cni.cncf.io/networks":"sriov-conf-1"},"name":"pod-case-03","namespace":...
Status:       Pending
IP:           
Containers:
  pod-case-03:
    Container ID:  
    Image:         centos/tools
    Image ID:      
    Port:          <none>
    Host Port:     <none>
    Command:
      /sbin/init
    State:          Waiting
      Reason:       ContainerCreating
    Ready:          False
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-k52z9 (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  default-token-k52z9:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-k52z9
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason                  Age                       From             Message
  ----     ------                  ----                      ----             -------
  Warning  FailedCreatePodSandBox  3m38s (x1597 over 3h12m)  kubelet, master  (combined from similar events): Failed create pod sandbox: rpc error: code = Unknown desc = [failed to set up sandbox container "1ab737d326ac02dc180994dba6b0b35f1307e6bd9b3111527918a446fb5d6659" network for pod "pod-case-03": NetworkPlugin cni failed to set up pod "pod-case-03_default" network: Multus: Err adding pod to network "sriov-conf-1": Multus: error in invoke Delegate add - "sriov": netplugin failed but error parsing its diagnostic message "": unexpected end of JSON input, failed to clean up sandbox container "1ab737d326ac02dc180994dba6b0b35f1307e6bd9b3111527918a446fb5d6659" network for pod "pod-case-03": NetworkPlugin cni failed to teardown pod "pod-case-03_default" network: Multus: error in invoke Delegate del - "sriov": netplugin failed but error parsing its diagnostic message "": unexpected end of JSON input / Multus: error in invoke Conflist Del - "cbr0": error in getting result from DelNetworkList: failed to convert major version part "": strconv.Atoi: parsing "": invalid syntax]

**I use this NetworkAttachmentDefinition will cause the error.**

[root@master ~]# cat sriov-conf-1.yml
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: sriov-conf-1
spec:
  config: '{
    "cniVersion": "0.3.0",
    "type": "sriov",
    "if0": "ens2f3",
    "if0name": "sriov-net1",
    "ipam": {
       "type": "host-local",
       "subnet": "192.168.3.0/24",
       "rangeStart": "192.168.3.82",
       "rangeEnd": "192.168.3.86",
       "gateway": "192.168.3.4"
     }
  }'

**But ,when i change it to l2enable it works, as follows:**

[root@master ~]# cat sriov-conf-1.yml
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: sriov-conf-1
spec:
  config: '{
    "cniVersion": "0.3.0",
    "type": "sriov",
    "if0": "ens2f3",
    "if0name": "sriov-net1",
    "l2enable": true
}'

[root@master cbr0]# kubectl get pod
NAME          READY   STATUS    RESTARTS   AGE
pod-case-03   1/1     Running   0          11m
[root@master cbr0]# kubectl exec -it pod-case-03 ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
3: eth0@if1998: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue state UP group default 
    link/ether 0e:92:1c:b8:79:bb brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet 10.244.0.199/24 scope global eth0
       valid_lft forever preferred_lft forever
37: sriov-net1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether ca:51:61:13:3e:83 brd ff:ff:ff:ff:ff:ff

**how can i assign a ip to the pod, thank you.**

**Comment by ahalim-intel** [comment]
May I ask, what version of sriov cni plugin you are running?

**Comment by ccmin** [comment]
thanks for ahalim-intel's comment.  fix it with new version.
