### ISSUE TITLE
VF MAC address collision

### ISSUE THREAD

**Issue by svallala** [intel/sriov-cni#125]
Intermittent ping failures

We persist the IP address and MAC address of a Pod. We generate a random MAC address in such a way that for a given IP address the MAC address remains the same.

SRIOV PodA, is assigned address IP-A and MAC address MAC-A. This is assigned to a VF on deployment. If the Pod were to restart, in our platform the pod will retain both IP-A and MAC-A, but the VF assigned for the Pod would have changed.

This is fine for a while, but we have seen that once in a while the MAC-A is assigned to the new VF and also to the host interface corresponding to the old VF that was released. In essence on the host we see two entities with MAC-A address. When this happens the ping to that container fails.

Multus: v3.4.1
Kubernetes: 1.16.3
SRIOV CNI: Latest

**Comment by killianmuldoon** [comment]
@svallala Can you please add the information under the bug template? The logs etc. will be useful in helping us figure out whether this issue is happening with sriov-cni or in one of the other components in your system.

**Comment by svallala** [comment]
These are some dmesg logs for a bond interface, but we have seen similar messages for normal VFs. Seems like there is a possibility where a MAC address assigned to a VF is not reset and then the kernel assigns a different address to avoid conflicts. When you assign the same custom MAC address, I am guessing this is resulting in conflicts.

If these logs are not enough to figure out the issue, I can provide logs with regular VF interfaces too.

[58244.718427] bond0: Releasing backup interface eth1
[58244.718432] bond0: the permanent HWaddr of eth1 - 1e:2e:1b:95:0e:a4 - is still in use by bond0 - set the HWaddr of eth1 to a different address to avoid conflicts
[58244.718437] bond0: making interface eth2 the new active one
[58244.728204] bond0: Releasing backup interface eth1
[58244.728216] bond0: the permanent HWaddr of eth1 - ee:b7:e4:43:89:d3 - is still in use by bond0 - set the HWaddr of eth1 to a different address to avoid conflicts
[58244.728227] bond0: making interface eth2 the new active one

**Comment by zshi-redhat** [comment]
Did the issue happen without bond involved?
What is the bond mode and fail_over_mac option used. Are eth1 and eth2 the slaves of bond0?
It might be helpful to provide information of `ip link show` output from contianer and host to check which MAC is conflicting on which interface.

**Comment by martinkennelly** [comment]
@svallala I am attempting to reproduce your issue.
Could you inform me what model name is your NIC, firmware version & driver version?

**Comment by svallala** [comment]
> Did the issue happen without bond involved?
> What is the bond mode and fail_over_mac option used. Are eth1 and eth2 the slaves of bond0?
> It might be helpful to provide information of `ip link show` output from contianer and host to check which MAC is conflicting on which interface.

Yes without a bonded interface. I will have to reproduce the issue to provide this information. The MAC address is present on the current VF that is assigned to a Pod and to an older VF that was used earlier and was supposed to be reset.

**Comment by svallala** [comment]
> @svallala I am attempting to reproduce your issue.
> Could you inform me what model name is your NIC, firmware version & driver version?

[root@qct-03 ~]# lspci | grep Ethernet
3b:00.0 Ethernet controller: Intel Corporation Ethernet Controller XXV710 for 25GbE SFP28 (rev 02)
3b:00.1 Ethernet controller: Intel Corporation Ethernet Controller XXV710 for 25GbE SFP28 (rev 02)

[root@qct-03 ~]# modinfo iavf
filename:       /lib/modules/3.10.0-1062.12.1.el7.x86_64/updates/drivers/net/ethernet/intel/iavf/iavf.ko
version:        3.7.61.20
license:        GPL
description:    Intel(R) Ethernet Adaptive Virtual Function Driver
author:         Intel Corporation, <linux.nics@intel.com>
alias:          i40evf
retpoline:      Y
rhelversion:    7.7
srcversion:     064B415812C3709830FEF1C
alias:          pci:v00008086d00001889sv*sd*bc*sc*i*
alias:          pci:v00008086d000037CDsv*sd*bc*sc*i*
alias:          pci:v00008086d00001571sv*sd*bc*sc*i*
alias:          pci:v00008086d0000154Csv*sd*bc*sc*i*
depends:
vermagic:       3.10.0-1062.12.1.el7.x86_64 SMP mod_unload modversions

[root@qct-03 ~]# modinfo i40e
filename:       /lib/modules/3.10.0-1062.12.1.el7.x86_64/updates/drivers/net/ethernet/intel/i40e/i40e.ko
version:        2.7.29
license:        GPL
description:    Intel(R) 40-10 Gigabit Ethernet Connection Network Driver
author:         Intel Corporation, <e1000-devel@lists.sourceforge.net>
retpoline:      Y
rhelversion:    7.7
srcversion:     2212C8D31172FBDBC9A1647
alias:          pci:v00008086d0000158Bsv*sd*bc*sc*i*
alias:          pci:v00008086d0000158Asv*sd*bc*sc*i*
alias:          pci:v00008086d000037D3sv*sd*bc*sc*i*
alias:          pci:v00008086d000037D2sv*sd*bc*sc*i*
alias:          pci:v00008086d000037D1sv*sd*bc*sc*i*
alias:          pci:v00008086d000037D0sv*sd*bc*sc*i*
alias:          pci:v00008086d000037CFsv*sd*bc*sc*i*
alias:          pci:v00008086d000037CEsv*sd*bc*sc*i*
alias:          pci:v00008086d00001588sv*sd*bc*sc*i*
alias:          pci:v00008086d00001587sv*sd*bc*sc*i*
alias:          pci:v00008086d000015FFsv*sd*bc*sc*i*
alias:          pci:v00008086d00001589sv*sd*bc*sc*i*
alias:          pci:v00008086d00001586sv*sd*bc*sc*i*
alias:          pci:v00008086d00001585sv*sd*bc*sc*i*
alias:          pci:v00008086d00001584sv*sd*bc*sc*i*
alias:          pci:v00008086d00001583sv*sd*bc*sc*i*
alias:          pci:v00008086d00001581sv*sd*bc*sc*i*
alias:          pci:v00008086d00001580sv*sd*bc*sc*i*
alias:          pci:v00008086d00001574sv*sd*bc*sc*i*
alias:          pci:v00008086d00001572sv*sd*bc*sc*i*
depends:        ptp
vermagic:       3.10.0-1062.12.1.el7.x86_64 SMP mod_unload modversions
parm:           debug:Debug level (0=none,...,16=all) (int)

**Comment by martinkennelly** [comment]
@svallala Can you show me ethtool -i ${ PF/VF interface name } so I can see the firmware version loaded?

**Comment by svallala** [comment]
[root@qct-03 ~]# ethtool -i enp59s0f0
driver: i40e
version: 2.7.29
firmware-version: 6.80 0x8000414f 1.1937.0
expansion-rom-version:
bus-info: 0000:3b:00.0
supports-statistics: yes
supports-test: yes
supports-eeprom-access: yes
supports-register-dump: yes
supports-priv-flags: yes
[root@qct-03 ~]# ethtool -i enp175s13f7
driver: iavf
version: 3.7.61.20
firmware-version: N/A
expansion-rom-version:
bus-info: 0000:af:0d.7
supports-statistics: yes
supports-test: no
supports-eeprom-access: no
supports-register-dump: no
supports-priv-flags: yes
[root@qct-03 ~]#

**Comment by martinkennelly** [comment]
@svallala I cannot reproduce your issue.
Can you post the pod spec which I assume includes your static mac?

**Comment by killianmuldoon** [comment]
closed as stale
