### ISSUE TITLE
Host reboots During POD deployment with wrong values in sriov plugin fields

### ISSUE THREAD

**Issue by subrnath** [intel/sriov-cni#13]
We are using this sriov plugin for Kubernetes POD with DPDK application. It's found that if there is wrong value in the network files for the sriov, host server reboots during POD deployment. For example following is our yaml file for the network definition.

plugin: sriov
args: '[
                {
                "name": "<name>",
                "type": "sriov",
                "if0": "<interface name>",
                "vlan": <vlan id>,
                "if0name": "<interface name>",
                "dpdk": {
                        "kernel_driver":"ixgbevf",
                        "dpdk_driver":"vfio-pci",
                        "dpdk_tool":"dpdk-devbind.py"
                }
        }
]'

if there is a wrong value input for any field like vfio_pci instead of vfio-pci, host server reboots during POD deployment.

**Comment by RahulG115** [comment]
check whether particular driver is loaded or not after reboot using $lsmod |grep <driver name>

**Comment by ahalim-intel** [comment]
Closing this issue now. Feel free to re-open if needed.
