### ISSUE TITLE
Need help to integrate sriov-cni + Multus in GKE (Google Kubernetes Engine)

### ISSUE THREAD

**Issue by ravikumar1907** [intel/sriov-cni#131]
## What issue would you like to bring attention to?
Integrating DPDK-SRIOV + Multus  with GKE 
## What is the impact of this issue?
No Impact. Need help if if any one integrated this with GKE/or with other Cloude Provider Managed K8S
## Do you have a proposed response or remediation for the issue?
No. I want some pointer / help if some one tried this with GKE.

**Comment by martinkennelly** [comment]
Can you provide documentation that this is possible on GKE?
I did a quick google and it seems SR-IOV is not an option on GKE but please tell me if this is not the case.

**Comment by ravikumar1907** [comment]
> Can you provide documentation that this is possible on GKE?
> I did a quick google and it seems SR-IOV is not an option on GKE but please tell me if this is not the case.

**Comment by ravikumar1907** [comment]
> Can you provide documentation that this is possible on GKE?
> I did a quick google and it seems SR-IOV is not an option on GKE but please tell me if this is not the case.

Yes it seems sriov is not supported with GKE and hence I'm failed to integrate this plugin GKE.
I don't have/find documentation that says this plugin supported in GKE

**Comment by martinkennelly** [comment]
I'm closing this issue because GKE doesn't seem to support SR-IOV.
