### ISSUE TITLE
Query about sharing DPDK device among 2 containers of a POD

### ISSUE THREAD

**Issue by PrahladaHerle** [intel/sriov-cni#136]
## What issue would you like to bring attention to?
Is it possible to share a single dpdk device among 2 containers in a POD (using SRIOV device plugin + SRIOV CNI)? If yes, how can we do that?

## What is the impact of this issue?
We want to run PRIMARY/SECONDARY applications in 2 different containers. This is not possible without solving above issue.

## Do you have a proposed response or remediation for the issue?
In case of SRIOV VF, if one container asks for an interface, same interface is visible in another container also (as the network namespace is shared). Is there any similar approach available for DPDK?

**Comment by zshi-redhat** [comment]
> 
> Is it possible to share a single dpdk device among 2 containers in a POD (using SRIOV device plugin + SRIOV CNI)? If yes, how can we do that?

This is currently not possible with sriov device plugin as one device will be count as one available resource, and be allocated once. If we want to allocate one device twice (to different container), we might want to count the single dpdk interface twice or more times.

> We want to run PRIMARY/SECONDARY applications in 2 different containers. This is not possible without solving above issue.


I didn't realize that we can run two dpdk applications (e.g. two testpmds) on the same SR-IOV device. Is there any permission issue when two application tries to use the same device?
@ahalim-intel @adrianchiris  can we?

**Comment by amorenoz** [comment]
AFAIK, not with VFIO

**Comment by PrahladaHerle** [comment]
Sure, this was more of an information that I was looking. DPDK device can't be shared across the container. Thanks for the quick response.
