### ISSUE TITLE
IPv6 on SR-IOV

### ISSUE THREAD

**Issue by udrwt** [intel/sriov-cni#18]
Hi,

If SR-IOV configured with multus, Does SR-IOV interface supports IPv6 only?

If i am trying to configure only IPv6, I am receiving below error.

> Multus: error in invoke Delegate add - "sriov": IPAM plugin returned missing IPv4 config.

**Comment by ahalim-intel** [comment]
This issue has been fixed in [Multus](https://github.com/intel/multus-cni/pull/212)
