### ISSUE TITLE
releaseVF fails

### ISSUE THREAD

**Issue by pkdas** [intel/sriov-cni#20]
In releaseVF 
- the VF is removed from DPDK 
- the vlan is set to 0
Between these two operations the VF interface is switched to i40evf driver before vlan can be set to 0. 
It appears if vlan is set before i40evf driver binding completes in the driver, the netlink.LinkSetVfVlan() fails and as a result the releaseVF returns without finishing up rest of the task. 

**This keeps the VF in an unusable state, causes VF resource leak. As the PODs deleted and re-created the SR-IOV CNI fails as it runs out of VFs.** 

Workaround is to allow a few seconds after unbinding from DPDK before clearing the VLAN.

454                 // bind the sriov vf to the kernel driver
455                 if err := enabledpdkmode(df, df.Ifname, false); err != nil {
456                         return fmt.Errorf("DPDK: failed to bind %s to kernel space: %s", df.Ifname, err)
457                 }
458
459                 // Workaround
460                 // unbinding from DPDK and binding to kernel driver takes a few seconds
461                 // the VLAN resetting call below is failing for i40e which takes couple of seconds
462                 **time.Sleep(4*time.Second)**
463
464                 // reset vlan for DPDK code here
465                 pfLink, err := netlink.LinkByName(conf.IF0)
466                 if err != nil {
467                         return fmt.Errorf("DPDK: master device %s not found: %v", conf.IF0, err)
468                 }
469
470                 if err = netlink.LinkSetVfVlan(pfLink, df.VFID, 0); err != nil {
471                         return fmt.Errorf("DPDK: failed to reset vlan tag for vf %d: %v", df.VFID, err)
472                 }
473
474                 return nil

**Comment by zshi-redhat** [comment]
Adding a sleep between driver switching and vlan setting might be solving the problem, but we may want to have a more deterministic way to say the dpdk driver has been successfully removed, otherwise the sleep time may vary among different systems and environments.

**Comment by ahalim-intel** [comment]
Closing this issue now. Feel free to re-open it if needed. Thanks
