### ISSUE TITLE
delegateDel fails when l2enable is True

### ISSUE THREAD

**Issue by pkdas** [intel/sriov-cni#27]
The network yaml is

apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: vccap-access
  namespace: mytest-demo
  annotations:
    k8s.v1.cni.cncf.io/resourceName: mytest/sriov
spec:
  config: '{
    "cniVersion": "0.3.0",
    "type": "sriov",
    "vlan": 200,
    "l2enable": true
  }'

We assign static IP address and the VF is bound to the i40evf driver 

===
Dec 13 21:16:36 skyhi1 kubelet[5783]: 2018-12-13T21:16:36-05:00 [debug] getKubernetesDelegate: &{0xc4203525a0}, &{vccap-access-host casa-cin3701   }, /etc/cni/multus/net.d
Dec 13 21:16:36 skyhi1 kubelet[5783]: 2018-12-13T21:16:36-05:00 [debug] getKubernetesDelegate: found resourceName annotation : vccap/sriov
Dec 13 21:16:36 skyhi1 kubelet[5783]: 2018-12-13T21:16:36-05:00 [debug] getKubernetesDelegate: podID: f71c4b8c-ff3a-11e8-9098-f8bc12195210 deviceID: 0000:19:02.5
Dec 13 21:16:36 skyhi1 kubelet[5783]: 2018-12-13T21:16:36-05:00 [debug] cniConfigFromNetworkResource: &TypeMeta{Kind:NetworkAttachmentDefinition,APIVersion:k8s.cni.cncf.io/v1,}, /etc/cni/multus/net.d
Dec 13 21:16:36 skyhi1 kubelet[5783]: 2018-12-13T21:16:36-05:00 [debug] getCNIConfigFromSpec: { "cniVersion": "0.3.0", "type": "sriov", "vlan": 3701, "l2enable": true }, access-host
Dec 13 21:16:36 skyhi1 kubelet[5783]: 2018-12-13T21:16:36-05:00 [debug] LoadDelegateNetConf: {"cniVersion":"0.3.0","deviceID":"0000:19:02.5","l2enable":true,"name":"vccap-access-host","type":"sriov","vlan":3701},

--- DelegateDel  is called ------------------

Dec 13 21:16:40 skyhi1 kubelet[5783]: 2018-12-13T21:16:40-05:00 [debug] delegateDel: <nil>, net2, &{{0.3.0 access-host sriov map[] {} {[]  [] []}} {  []}  false false [123 34 99 110 105 86 101 114 115 105 111 110 34 58 34 48 46 51 46 48 34 44 34 100 101 118 105 99 101 73 68 34 58 34 48 48 48 48 58 49 57 58 48 50 46 53 34 44 34 108 50 101 110 97 98 108 101 34 58 116 114 117 101 44 34 110 97 109 101 34 58 34 118 99 99 97 112 45 97 99 99 101 115 115 45 104 111 115 116 34 44 34 116 121 112 101 34 58 34 115 114 105 111 118 34 44 34 118 108 97 110 34 58 51 55 48 49 125]}, &{cf6bdd3a34705a36a609ac12ea554e1605f6da0d5cfe1d45bfbd7ed077d5c952 /proc/412754/ns/net net2 [[IgnoreUnknown 1] [K8S_POD_NAMESPACE casa-cin3701] [K8S_POD_NAME vccap-cp-0] [K8S_POD_INFRA_CONTAINER_ID cf6bdd3a34705a36a609ac12ea554e1605f6da0d5cfe1d45bfbd7ed077d5c952]] map[] }, /opt/cni/bin
Dec 13 21:16:40 skyhi1 kubelet[5783]: 2018-12-13T21:16:40-05:00 [error] Multus: error in invoke Delegate del - "sriov": unable to get shared PF device: Link not found
Dec 13 21:16:40 skyhi1 kubelet[5783]: E1213 21:16:40.971868    5783 cni.go:280] Error deleting network: Multus: error in invoke Delegate del - "sriov": unable to get shared PF device: Link not found

---- Looking at SRIOV.go (k8s-deviceid-model)
ReleaseVF

	if conf.L2Mode != false {
		//check for the shared vf net interface
		ifName := podifName + "d1"
		_, err := netlink.LinkByName(ifName)

		if err != nil {
			return fmt.Errorf("unable to get shared PF device: %v", err)
		}
		conf.Sharedvf = true
	}
Looks like netlink.LinkByName() is always going fail. What is ifName := podifName + "d1" and shared vf net interface. Is this code stale?

Has anyone else seeing similar issues?

**Comment by zshi-redhat** [comment]
I tried and got similar errors, one is from sriov-cni, just as described in above problem description, the second is from Multus:

---
  Warning  FailedCreatePodSandBox  3s               kubelet, nfvsdn-17.oot.lab.eng.rdu2.redhat.com  Failed create pod sandbox: rpc error: code = Unknown desc = failed to set up sandbox container "021a516464e97e1d42190d9f962f4a41596bf0339a25b1365a850796dcb4bb5d" network for pod "testpod2": NetworkPlugin cni failed to set up pod "testpod2_default" network: Multus: Err in setting  networks status: error convert the type.Result to current.Result: cannot convert: no valid IP addresses
---

Regarding the first error:

This looks like a bug in sriov-cni where it's meant to check whether Sharedvf is enabled when conf.L2Mode is configured. but it shall not return error if Sharedvf is not used, instead it may only want to set Sharedvf=true when Sharedvf is detected. for example:

```
        if conf.L2Mode != false {
                //check for the shared vf net interface
                ifName := podifName + "d1"
                _, err := netlink.LinkByName(ifName)
                if err == nil {
                        fmt.Printf("Get shared PF device: %s", ifName)
                        conf.Sharedvf = true
                }
        }
```

The interface name `ifName` above is valid when Sharedvf is used, it will be set to 'podifName + d1' at [here](https://github.com/intel/sriov-cni/blob/master/sriov/sriov.go#L146) when cmdAdd is invoked.


Re the second Multus error:

It looks like Multus expects an IPAM result be returned to [update network status](https://github.com/intel/multus-cni/blob/master/multus/multus.go#L339) in pod annotation, but with L2Mode enabled, IPAM is not configured.  @s1061123 do you know if IPAM result is mandatory to 
be returned in order for multus to update network status?

**Comment by ahalim-intel** [comment]
> It looks like Multus expects an IPAM result be returned to [update network status](https://github.com/intel/multus-cni/blob/master/multus/multus.go#L339) in pod annotation, but with L2Mode enabled, IPAM is not configured. @s1061123 do you know if IPAM result is mandatory to
> be returned in order for multus to update network status?

You are spot in @zshi-redhat Multus now expect all delegate plugins to provide valid IPAM information or else it throws error. Similar case with sriov-cni in DPDK mode.

Please see https://github.com/intel/multus-cni/issues/211 
and PR with Fix: https://github.com/intel/multus-cni/pull/212
