### ISSUE TITLE
MaxSharedVf functionality not explained

### ISSUE THREAD

**Issue by pkdas** [intel/sriov-cni#28]
MaxSharedVf is documented and the value is set 2.
Is this a config param that can be set? Could you provide some documentation/explanation on  sharedVF?
Is this something to do with a VF being shared on with different VLANs or with and without VLAN?
What is the use case?

**Comment by pkdas** [comment]
We are using sriov-device-plugin which assigns the VFs. The NIC we are using is i40e and 16-32 VFs are created on one single PF. 

Could you provide the info on the NICs (model, make) where single VF belongs to multiple PFs?

**Comment by ahalim-intel** [comment]
Before sriov-device-plugin the sriov-cni used to handle VF allocation. We still need to support this for backward compatibility.

Some Mellnox NIC support this feature. See [this doc](http://www.mellanox.com/related-docs/prod_software/Mellanox_EN_for_Linux_User_Manual_v4_0.pdf) [ Page 75 under section: 3.2.1.2.1 Configuring SR-IOV for ConnectX-3/ConnectX-3 Pro ]
