### ISSUE TITLE
POD with fails SRIOV-VFs after server reboot 

### ISSUE THREAD

**Issue by pkdas** [intel/sriov-cni#34]
Have 3 or 4 PODs with SRIOV-VFs and reboot the server. At system startup (assume the VFs are created), kubelet starts all these PODs pretty much at the same time. Multus/SRIOV plugins are called for the VFs and multiple VF requests hit the i40e/i40evf driver on the host at the same time. And VF configuration fails since the drivers can not handle multiple requests, VLAN config fails or SRIOV plugin add fail randomly.

Looks like the SRIOV plugin add/release VF requests need to be serialised and locked.

**Comment by zshi-redhat** [comment]
I think serialization is done in Multus which delegate the plugins one by one, even if there are multiple network objects attached to single pod. can you please provide some detailed log message from both driver side and SR-IOV plugins for reference? Thanks!

**Comment by pkdas** [comment]
I don't think multus does serialisation across PODs. If POD1 and POD2 are scheduled at the same time and all these PODs use VFs and configure VLANs, DPDK etc and banging on the same i40e PF driver,many of the netlink operations will fail since those take finite amount of time to complete and i40e drivers are can not handle concurrent VF control/configuration requests.

The workaround I found is to give POD1 and POD2 different priorities so the Kube controller schedules them one by one.

**Comment by killianmuldoon** [comment]
@pkdas do you have steps for replication of this?

**Comment by killianmuldoon** [comment]
Closed as stale.
