### ISSUE TITLE
SRIOV plugin fails - does not support CNI 0.3.0

### ISSUE THREAD

**Issue by pkdas** [intel/sriov-cni#35]
Multus: Err in tearing down failed plugins: Multus: error in invoke Delegate add - "sriov": incompatible CNI versions; config is "0.3.0", plugin supports ["0.1.0" "0.2.0"]

**Comment by pkdas** [comment]
Does it mean we have to use CNI 0.2.0 for all CNI plugin including Multus

piVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: intmgmt
  namespace: demo
  annotations:
    k8s.v1.cni.cncf.io/resourceName: sriov
spec:
  config: '{
    "cniVersion": "0.3.0",
    "vlan": 400,
    "type": "sriov",
    "l2enable": true
  }'

**Comment by ahalim-intel** [comment]
Documentation doesn't suggest to add "cniVersion". Other error is same as you have already seen sriov-cni with dpdk config - multus throwing in error for no IPAM. Please log these issue for Multus.
