### ISSUE TITLE
make does not build the latest code

### ISSUE THREAD

**Issue by pkdas** [intel/sriov-cni#36]
make clean is always required before make

~/github/intel/sriov-cni$
modify sriov/sriov.go
~/github/intel/sriov-cni$make
running gofmt...
running golint...
This does not build the SRIOV plugin
~/github/intel/sriov-cni$make clean
~/github/intel/sriov-cni$make
github.com/intel/sriov-cni/sriov
Building sriov...
Done!

**Comment by zshi-redhat** [comment]
fixed by #53 , it should work as expected now, please feel free to reopen if not.
