### ISSUE TITLE
Support moveing VF which is eth0 on the host to the namespace

### ISSUE THREAD

**Issue by Mmduh-483** [intel/sriov-cni#40]
When using multus pluing the first interface will be eth0 and
the others will be netX. We need to make sure that before
we move VF which is eth0 to the container namespace it should
first be renamed to temp name before moving to the namespace.
This is to avoid conflict with the eth0 interface which already
exist in the namespace.

**Comment by zshi-redhat** [comment]
If ``if0name`` is provided, it's checked to ensure the given interface name is not in the list of "eth0, eth1, lo";
but the ``if0name`` is configured after VF be moved into pod namespace, so there is chance that the original VF name conflicts with the default network interface name when moving to pod namespace.

**Comment by moshe010** [comment]
So we have fix for that I will request Mmduh-483 to upload it
