### ISSUE TITLE
Failed to build on golang v1.6 and glide v0.13.1

### ISSUE THREAD

**Issue by mJace** [intel/sriov-cni#60]
Hello,  
  
Are you still build this based on golang v1.5+?  
I have some error like  
`obj.IsAlias undefined (type *types.TypeName has no field or method IsAlias)`
 during building with golang v1.6  

And after I upgraded my golang to v1.10, the I am able to build this successfully.

**Comment by zshi-redhat** [comment]
I didn't try with golang version < 1.10; my local build works with v1.10.3;
maybe the README is outdated and we should update it to golang v1.10+.

**Comment by killianmuldoon** [comment]
@zshi-redhat I think we should try to do this the next time we're altering the repo - not sure we're enforcing go 1.5 standards in new PRs.

**Comment by killianmuldoon** [comment]
Updated as of #127
