### ISSUE TITLE
Have separate log level/file/tracing for SRIOV plugin

### ISSUE THREAD

**Issue by pkdas** [intel/sriov-cni#68]
Currently SRIOV errors are reported via Multus log file /var/log/multus.log when an error occurs in SRIOV plugin. If I set log level to debug in Multus all debug logs are dumped and it becomes cumbersome to navigate. Essentially I am looking for a way to trace/debug SRIOV plugin only and not interested in Multus logs/debug logs. We should be able  set trace/debug level for SRIOV only.

**Comment by killianmuldoon** [comment]
@pkdas since SRIOV-CNI doesn't do any logging of its own this might be a better issue for multus. Maybe tagging logs with the source cni so that some sort of filtering can be done? Right now I tend to use cat | grep  - but I can see that's not ideal
