### ISSUE TITLE
move SR-IOV VF creation steps into device plugin

### ISSUE THREAD

**Issue by ahalim-intel** [intel/sriov-cni#74]
The steps explaining how to create virtual functions for a SRIOV capable nic no longer should be part of the sriov-cni. These steps should be carried out before device plugin is run. So, I think we should move all VF creation steps into [SR-IOV device plugin](https://github.com/ahalim-intel/sriov-network-device-plugin) documentation.

**Comment by killianmuldoon** [comment]
@ahalim-intel this can be closed, right ?

**Comment by ahalim-intel** [comment]
There is no docs for creating VFs in the SR-IOV network device plugin atm. As VFs needs to be created before device plugin is run, it make sense to move these steps in there. The linked PR above also should go to the same location.

**Comment by killianmuldoon** [comment]
Implemented at https://github.com/intel/sriov-network-device-plugin/pull/240
