### ISSUE TITLE
Poor DPDK Performance

### ISSUE THREAD

**Issue by cliffburdick** [intel/sriov-cni#75]
Hi, I'm using this plugin with the mellanox connectx-5 100G card with DPDK. On bare metal with SRIOV off, I can hit 100Gbps with 2 transmitting threads with 4KB packets. When I use this plugin, I'm not able to get higher than about 70Gbps, regardless of how many threads I have sending out the VFs. I've tried both more queues per VF, and more VFs on the same interface to no avail. All transmitting cores are on the same NUMA node.

Since it's mellanox, I don't specific dpdk in the CRD because of their bifurcated driver. Dpdk recognizes the devices properly, so I didn't think that was the cause either. Does anyone have any ideas to try?

**Comment by ahalim-intel** [comment]
@cliffburdick 
How do you compare the results? Is this performance in Container vs non-container/VM?
I'm trying to understand the the real cause. The sriov-cni and sriov device plugin does nothing special to improve or degrade a NIC's performance. They are used to bring the interfaces up in the container environment.

**Comment by ahalim-intel** [comment]
@Mmduh-483 @moshe010 
Any input on this from your sides?

**Comment by moshe010** [comment]
@cliffburdick, Did you open a support case for Mellanox on this?
I think it is better to work with them so they can validate that you have  all the required tuning

**Comment by cliffburdick** [comment]
Hi @ahalim-intel , the first case was SR-IOV off in a container with host networking on. The physical device was used. I'm wondering if it's a configuration issue on my end, so I will close this for now and go back try trace the root problem. Thanks.
