### ISSUE TITLE
Add capability of directly assigning PFs to Pods

### ISSUE THREAD

**Issue by Levovar** [intel/sriov-cni#8]
The original SRIOV-CNI was enhanced with the capability of directly assigning PFs to Pods:
https://github.com/hustcat/sriov-cni/commit/793ec5dcc67fc5ec54d4bd244461a7baf8950609

The use-cases -mostly TelCo related- mentioned by the commit are still valid, and could be satisfied with the merging of the code, and the introduction of the pfOnly configuration parameter.

The code could be further enhanced by defining the interworking between the newly introduced pfOnly, and the already existing dpdk configuration options.
When both are defined the plugin could first bind the PF directly to the configured DPDK kernel driver, then assign it to the Pod via its PCI address.
Such enhancement would basically unite the best of both plugins: capability of directly assigning PFs to Pods, but via the PFs PCI address, while also taking care of the management of the PF's control plane.

I don't think the existing plugin can serve this use-case right now, but feel free to correct me if I missed something! 
I (and/or some of my colleagues) could also handle the contribution in case the idea is welcomed, but I wanted to open a discussion about it first.

**Comment by booxter** [comment]
I would also love to see this feature.

In Kubevirt case, we need to be able to safely validate SR-IOV for our cluster. in CI environment, Kubevirt cluster is running inside an OpenShift pod. To be able to validate SR-IOV support for Kubevirt, we need to be able to deploy SR-IOV device plugin and CNI inside this pod. It means that we should first propagate PFs into the pod. We would like to use SR-IOV DP / CNI for that. Basically, we would have SR-IOV DP / CNI running in two places: 1) at the bottom layer to propagate PF into CI pod; and 2) as part of Kubevirt cluster, to allocate VFs from allocated PFs to virtual machines.

We were looking into building some custom mechanism to propagate PFs into CI pods, but figured that maybe we can reuse the same components on both layers.

**Comment by zshi-redhat** [comment]
With the combined use of SR-IOV Device Plugin (SriovMode being False) and SR-IOV CNI, I think we could plug PF interface to container now, @booxter @Levovar do you think this can satisfy your requirements?

**Comment by zshi-redhat** [comment]
Thanks @Levovar for the confirmation!
Closing this issue, feel free to re-open if any problem.

**Comment by sseetharaman6** [comment]
@zshi-redhat, I don't see a `pfOnly` option in the current master of SR-IOV CNI.  Could you point me to it? SRIOV DP is able to detect the PF when I set `"sriovMode" : false"` , but the SRIOV CNI is failing while creating the pod with this error :
```Multus: Err in tearing down failed plugins: Multus: error in invoke Delegate add - "sriov": SRIOV-CNI failed to load netconf: lstat /sys/bus/pci/devices/0000:01:00.0/physfn/net: no such file or directory```
Could you help?
