### ISSUE TITLE
Supporting SR-IOV non-capable devices

### ISSUE THREAD

**Issue by Gylleus** [intel/sriov-cni#83]
Hi,

I know it goes a bit against the name of this CNI, but are there any plans on supporting devices that are not using SR-IOV? For my team it would be useful in a few different scenarios.

I noticed that Intel SRIOV network device plugin that this CNI works with seems to support non-capable network devices from looking at the README (seems to have been updated recently though). The CNI itself does not seem to support it, however, so are there any plans for it in the future?

**Comment by zshi-redhat** [comment]
> Hi,
> 
> I know it goes a bit against the name of this CNI, but are there any plans on supporting devices that are not using SR-IOV? For my team it would be useful in a few different scenarios.

What are those devices not using SR-IOV? can you list a few?

> 
> I noticed that Intel SRIOV network device plugin that this CNI works with seems to support non-capable network devices from looking at the README (seems to have been updated recently though). The CNI itself does not seem to support it, however, so are there any plans for it in the future?

**Comment by Gylleus** [comment]
Correct me if I am wrong but not all NICs support SR-IOV. Since I do not know on which hardware will be used when users deploy my platform I am not sure that it is valid to assume that they will have SR-IOV support on their interfaces.

Another example is when deploying a Kubernetes cluster inside VMs that either have totally virtual interfaces or VFs provided to them through SR-IOV from the baremetal host machine. In this case the VMs can to my knowledge use SR-IOV on its interface. The only way that would be possible would be through PCI-passthrough of the physical NICs to individual VMs.

**Comment by zshi-redhat** [comment]
> Correct me if I am wrong but not all NICs support SR-IOV. Since I do not know on which hardware will be used when users deploy my platform I am not sure that it is valid to assume that they will have SR-IOV support on their interfaces.

In this case, you may need a device plugin that can discover and advertise non SR-IOV capable devices;
then request this type of device in the pod spec.
Looking at the SR-IOV device plugin code, given a non SR-IOV capable device, it will also be discovered and exposed.


> 
> Another example is when deploying a Kubernetes cluster inside VMs that either have totally virtual interfaces or VFs provided to them through SR-IOV from the baremetal host machine. In this case the VMs can to my knowledge use SR-IOV on its interface. The only way that would be possible would be through PCI-passthrough of the physical NICs to individual VMs.

I believe this is a similar request to this [issue](https://github.com/intel/sriov-network-device-plugin/issues/133), please also refer to previous discussion [here](https://github.com/intel/sriov-network-device-plugin/issues/127).
