### ISSUE TITLE
how do sriov enabled pods connect across nodes?

### ISSUE THREAD

**Issue by hymgg** [intel/sriov-cni#89]
Hello,

With the multus-cni, sriov-cni, sriov-device-plugin, we could start multiple pods on same node, and they could connect to each other, using host-local or static ipam.

How do pods connect across different nodes?

Say we have pod1 on node1 with static ip 10.1.1.101, pod2 on node2 with static ip 10.1.1.102, pod3 on node3 with static ip 10.1.1.103, how do they connect?

example:

apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: sriov-net-4
  namespace: mtx-test10
  annotations:
    k8s.v1.cni.cncf.io/resourceName: intel.com/sriov_net_A
spec:
  config: '{
  "type": "sriov",
  "name": "sriov-network-4",
  "ipam": {
    "type": "static"
  }
}'

--

apiVersion: v1
kind: Pod
metadata:
  name: testpod1
  namespace: mtx-test10
  annotations:
    k8s.v1.cni.cncf.io/networks: '[
            { "name": "sriov-net-4",
              "ips": "10.1.1.101/24"
            }
    ]'
spec:
  containers:
  - name: appcntr1 
    image: centos/tools 
    imagePullPolicy: IfNotPresent
    command: [ "/bin/bash", "-c", "--" ]
    args: [ "while true; do sleep 300000; done;" ]
    resources:
      requests:
        intel.com/sriov_net_A: '1' 
      limits:
        intel.com/sriov_net_A: '1'
  nodeName: mtx-hw3-bld01

--

apiVersion: v1
kind: Pod
metadata:
  name: testpod2
  namespace: mtx-test10
  annotations:
    k8s.v1.cni.cncf.io/networks: '[
            { "name": "sriov-net-4",
              "ips": "10.1.1.102/24"
            }
    ]'
spec:
  containers:
  - name: appcntr1 
    image: centos/tools 
    imagePullPolicy: IfNotPresent
    command: [ "/bin/bash", "-c", "--" ]
    args: [ "while true; do sleep 300000; done;" ]
    resources:
      requests:
        intel.com/sriov_net_A: '1' 
      limits:
        intel.com/sriov_net_A: '1'
  nodeName: mtx-hw3-bld02

Thanks.  -Jessica

**Comment by zshi-redhat** [comment]
@hymgg hi, are you looking for a ipam plugin that is capable of allocating unique IPs across cluster nodes? or an external SDN entity that can connect different nodes via switches.

**Comment by hymgg** [comment]
@zshi-redhat need unique IPs across cluster nodes, and connection among those IPs, so the application pods have a private network for some heavy traffic, please advice how to achieve that on top of the sriov-cni. Thanks.  -Jessica

**Comment by zshi-redhat** [comment]
> @zshi-redhat need unique IPs across cluster nodes / pods, and connection among those IPs, so the application pods have a private network for some heavy traffic, please advice how to achieve that on top of the sriov-cni.

what about using dhcp ipam plugin for IP allocation?
another option I know is from Doug's project called [whereabouts](https://github.com/dougbtv/whereabouts).

> 
> In the example above, I could use static ipam to give each pod a unique IP, but how do I get the pods from different nodes to connect on those IPs? 

I think the ideal way is to create a service with those pods as backend and applications communicate with each other via service. however this is not yet supported on sidecar interfaces. but I remember this is one of the features discussed in NPWG working group.

There is no automated way for a pod to know the IP address of another pod afaik.
however all the IP addresses for a pod have been published by Multus in Pod annotation, you probably can get those IPs from there.

> The underlying PFs from the nodes are wired to a network. How do we enable routing for the VFs?

This is a really good one, I don't think we have ever discuss this question. @ahalim-intel any ideas?

> 
> Thanks. -Jessica

**Comment by Levovar** [comment]
another option is to try out DANM as your metaplugin (https://github.com/nokia/danm), which supports this IP allocation out of the box, and also supports this SR-IOV CNI as a backend

**Comment by hymgg** [comment]
Thank you guys.

Whether dhcp or static, we still need to figure out routing/connection across nodes on sriov network. Services / headless services on secondary networks would help.

Gonna take a look at DANM.

Not sure if this is the right place to continue the discussion, we're a ISV for telcos, our core engine is a cluster with 3 networks by default, the mgmt network, the data network for incoming traffic, the very chatty transaction protocol network to keep cluster members in sync -- usually on 40Gig. Looking for a way to achieve that with k8s.

Thanks.  -Jessica

**Comment by killianmuldoon** [comment]
@hymgg did you find a solution to this?

**Comment by hymgg** [comment]
@killianmuldoon yes, DANM worked for us.
